/**
 * @ngdoc overview
 * @name <%= config.get('name') %>-demo
 *
 * @description
 * Generated by Yo men
 *
 * **Note:** Describe what this module does
 *
 * @example
  http://localhost:8000
 */

angular.module('<%= config.get("name") %>-demo', [ 'ngRoute' ])
.config([ '$routeProvider', '$locationProvider', function($routeProvider,$locationProvider) {

    $routeProvider
      .when('/', {
        templateUrl: 'demo/main.html',
        controller: 'demoCtrl'
      })
      .otherwise({
        redirectTo: '/'
      });

    $locationProvider.html5Mode(true);

}]);
